/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { CautionBlockUpdateType } from './cautionBlockUpdateType';
import type { CautionBlockUpdateConfig } from './cautionBlockUpdateConfig';
import type { CautionBlockUpdateContent } from './cautionBlockUpdateContent';
import type { CautionBlockUpdateOrderIndex } from './cautionBlockUpdateOrderIndex';

export interface CautionBlockUpdate {
  type?: CautionBlockUpdateType;
  config?: CautionBlockUpdateConfig;
  content?: CautionBlockUpdateContent;
  order_index?: CautionBlockUpdateOrderIndex;
}
