/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ChecklistBlockUpdateType } from './checklistBlockUpdateType';
import type { ChecklistBlockUpdateConfig } from './checklistBlockUpdateConfig';
import type { ChecklistBlockUpdateContent } from './checklistBlockUpdateContent';
import type { ChecklistBlockUpdateOrderIndex } from './checklistBlockUpdateOrderIndex';

export interface ChecklistBlockUpdate {
  type?: ChecklistBlockUpdateType;
  config?: ChecklistBlockUpdateConfig;
  content?: ChecklistBlockUpdateContent;
  order_index?: ChecklistBlockUpdateOrderIndex;
}
