/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ChecklistConfigDescription } from './checklistConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { ChecklistConfigDisplay } from './checklistConfigDisplay';
import type { ChecklistConfigChecklist } from './checklistConfigChecklist';

export interface ChecklistConfig {
  label: string;
  description: ChecklistConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: ChecklistConfigDisplay;
  checklist: ChecklistConfigChecklist;
}
