/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */

export interface ContentBlockOrderItem {
  /** Content block UUID */
  id: string;
  /**
   * New order position (1-based)
   * @minimum 1
   */
  order_index: number;
}
