/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { DateBlockUpdateType } from './dateBlockUpdateType';
import type { DateBlockUpdateConfig } from './dateBlockUpdateConfig';
import type { DateBlockUpdateContent } from './dateBlockUpdateContent';
import type { DateBlockUpdateOrderIndex } from './dateBlockUpdateOrderIndex';

export interface DateBlockUpdate {
  type?: DateBlockUpdateType;
  config?: DateBlockUpdateConfig;
  content?: DateBlockUpdateContent;
  order_index?: DateBlockUpdateOrderIndex;
}
