/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { DescriptionBlockUpdateType } from './descriptionBlockUpdateType';
import type { DescriptionBlockUpdateConfig } from './descriptionBlockUpdateConfig';
import type { DescriptionBlockUpdateContent } from './descriptionBlockUpdateContent';
import type { DescriptionBlockUpdateOrderIndex } from './descriptionBlockUpdateOrderIndex';

export interface DescriptionBlockUpdate {
  type?: DescriptionBlockUpdateType;
  config?: DescriptionBlockUpdateConfig;
  content?: DescriptionBlockUpdateContent;
  order_index?: DescriptionBlockUpdateOrderIndex;
}
