/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { DescriptionConfigDescription } from './descriptionConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { DescriptionConfigDisplay } from './descriptionConfigDisplay';
import type { DescriptionConfigFormatting } from './descriptionConfigFormatting';

export interface DescriptionConfig {
  label: string;
  description: DescriptionConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: DescriptionConfigDisplay;
  formatting: DescriptionConfigFormatting;
}
