/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { FileUploadBlockUpdateType } from './fileUploadBlockUpdateType';
import type { FileUploadBlockUpdateConfig } from './fileUploadBlockUpdateConfig';
import type { FileUploadBlockUpdateContent } from './fileUploadBlockUpdateContent';
import type { FileUploadBlockUpdateOrderIndex } from './fileUploadBlockUpdateOrderIndex';

export interface FileUploadBlockUpdate {
  type?: FileUploadBlockUpdateType;
  config?: FileUploadBlockUpdateConfig;
  content?: FileUploadBlockUpdateContent;
  order_index?: FileUploadBlockUpdateOrderIndex;
}
