/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { FlowCreateDescription } from './flowCreateDescription';
import type { FlowCreateDurationDays } from './flowCreateDurationDays';
import type { FlowCreateStatus } from './flowCreateStatus';

export interface FlowCreate {
  name: string;
  description?: FlowCreateDescription;
  duration_days?: FlowCreateDurationDays;
  status?: FlowCreateStatus;
}
