/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { HeaderConfigDescription } from './headerConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { HeaderConfigDisplay } from './headerConfigDisplay';
import type { HeaderConfigStyle } from './headerConfigStyle';

export interface HeaderConfig {
  label: string;
  description: HeaderConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: HeaderConfigDisplay;
  style: HeaderConfigStyle;
}
