/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ListConfigDescription } from './listConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { ListConfigDisplay } from './listConfigDisplay';
import type { ListConfigList } from './listConfigList';

export interface ListConfig {
  label: string;
  description: ListConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: ListConfigDisplay;
  list: ListConfigList;
}
