/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { MediaBlockUpdateType } from './mediaBlockUpdateType';
import type { MediaBlockUpdateConfig } from './mediaBlockUpdateConfig';
import type { MediaBlockUpdateContent } from './mediaBlockUpdateContent';
import type { MediaBlockUpdateOrderIndex } from './mediaBlockUpdateOrderIndex';

export interface MediaBlockUpdate {
  type?: MediaBlockUpdateType;
  config?: MediaBlockUpdateConfig;
  content?: MediaBlockUpdateContent;
  order_index?: MediaBlockUpdateOrderIndex;
}
