/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { MediaConfigDescription } from './mediaConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { MediaConfigDisplay } from './mediaConfigDisplay';
import type { MediaConfigMedia } from './mediaConfigMedia';

export interface MediaConfig {
  label: string;
  description: MediaConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: MediaConfigDisplay;
  media: MediaConfigMedia;
}
