/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { NewHireUpdateFirstName } from './newHireUpdateFirstName';
import type { NewHireUpdateLastName } from './newHireUpdateLastName';
import type { NewHireUpdateStatus } from './newHireUpdateStatus';

export interface NewHireUpdate {
  first_name?: NewHireUpdateFirstName;
  last_name?: NewHireUpdateLastName;
  status?: NewHireUpdateStatus;
}
