/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { OnboardingSessionCompanyLogoUrl } from './onboardingSessionCompanyLogoUrl';
import type { OnboardingSessionCurrentStageId } from './onboardingSessionCurrentStageId';
import type { OnboardingSessionStartedAt } from './onboardingSessionStartedAt';
import type { OnboardingSessionCompletedAt } from './onboardingSessionCompletedAt';
import type { StageProgress } from './stageProgress';

export interface OnboardingSession {
  session_token: string;
  new_hire_id: string;
  flow_id: string;
  flow_name: string;
  company_name: string;
  company_logo_url?: OnboardingSessionCompanyLogoUrl;
  new_hire_name: string;
  new_hire_email: string;
  status: string;
  current_stage_id?: OnboardingSessionCurrentStageId;
  started_at?: OnboardingSessionStartedAt;
  completed_at?: OnboardingSessionCompletedAt;
  stages?: StageProgress[];
}
