/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { RatingScaleConfigDescription } from './ratingScaleConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { RatingScaleConfigDisplay } from './ratingScaleConfigDisplay';
import type { RatingScaleConfigRating } from './ratingScaleConfigRating';

export interface RatingScaleConfig {
  label: string;
  description: RatingScaleConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: RatingScaleConfigDisplay;
  rating: RatingScaleConfigRating;
}
