/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { SingleChoiceConfigDescription } from './singleChoiceConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { SingleChoiceConfigDisplay } from './singleChoiceConfigDisplay';
import type { SingleChoiceConfigQuestion } from './singleChoiceConfigQuestion';

export interface SingleChoiceConfig {
  label: string;
  description: SingleChoiceConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: SingleChoiceConfigDisplay;
  question: SingleChoiceConfigQuestion;
}
