/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { StageProgressDescription } from './stageProgressDescription';
import type { StageProgressType } from './stageProgressType';
import type { ContentBlockProgress } from './contentBlockProgress';
import type { StageProgressStartedAt } from './stageProgressStartedAt';
import type { StageProgressCompletedAt } from './stageProgressCompletedAt';

export interface StageProgress {
  id: string;
  name: string;
  description?: StageProgressDescription;
  order: number;
  type?: StageProgressType;
  status: string;
  content_blocks?: ContentBlockProgress[];
  is_complete: boolean;
  started_at?: StageProgressStartedAt;
  completed_at?: StageProgressCompletedAt;
}
