/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TextAreaConfigDescription } from './textAreaConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { TextAreaConfigDisplay } from './textAreaConfigDisplay';
import type { TextAreaConfigInput } from './textAreaConfigInput';

export interface TextAreaConfig {
  label: string;
  description: TextAreaConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: TextAreaConfigDisplay;
  input: TextAreaConfigInput;
}
