/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TextInputBlockUpdateType } from './textInputBlockUpdateType';
import type { TextInputBlockUpdateConfig } from './textInputBlockUpdateConfig';
import type { TextInputBlockUpdateContent } from './textInputBlockUpdateContent';
import type { TextInputBlockUpdateOrderIndex } from './textInputBlockUpdateOrderIndex';

export interface TextInputBlockUpdate {
  type?: TextInputBlockUpdateType;
  config?: TextInputBlockUpdateConfig;
  content?: TextInputBlockUpdateContent;
  order_index?: TextInputBlockUpdateOrderIndex;
}
