/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TimePickerConfigDescription } from './timePickerConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { TimePickerConfigDisplay } from './timePickerConfigDisplay';
import type { TimePickerConfigTime } from './timePickerConfigTime';

export interface TimePickerConfig {
  label: string;
  description: TimePickerConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: TimePickerConfigDisplay;
  time: TimePickerConfigTime;
}
