/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { HeaderBlockUpdate } from './headerBlockUpdate';
import type { DescriptionBlockUpdate } from './descriptionBlockUpdate';
import type { MediaBlockUpdate } from './mediaBlockUpdate';
import type { SingleChoiceBlockUpdate } from './singleChoiceBlockUpdate';
import type { MultipleChoiceBlockUpdate } from './multipleChoiceBlockUpdate';
import type { TextInputBlockUpdate } from './textInputBlockUpdate';
import type { TextAreaBlockUpdate } from './textAreaBlockUpdate';
import type { FileUploadBlockUpdate } from './fileUploadBlockUpdate';
import type { ExternalLinkBlockUpdate } from './externalLinkBlockUpdate';
import type { ChecklistBlockUpdate } from './checklistBlockUpdate';
import type { CautionBlockUpdate } from './cautionBlockUpdate';
import type { ListBlockUpdate } from './listBlockUpdate';
import type { DateBlockUpdate } from './dateBlockUpdate';
import type { TimePickerBlockUpdate } from './timePickerBlockUpdate';
import type { RatingScaleBlockUpdate } from './ratingScaleBlockUpdate';
import type { VisualAudioBlockUpdate } from './visualAudioBlockUpdate';

export type UpdateContentBlockApiContentBlocksContentBlocksContentBlockIdPutBody = HeaderBlockUpdate | DescriptionBlockUpdate | MediaBlockUpdate | SingleChoiceBlockUpdate | MultipleChoiceBlockUpdate | TextInputBlockUpdate | TextAreaBlockUpdate | FileUploadBlockUpdate | ExternalLinkBlockUpdate | ChecklistBlockUpdate | CautionBlockUpdate | ListBlockUpdate | DateBlockUpdate | TimePickerBlockUpdate | RatingScaleBlockUpdate | VisualAudioBlockUpdate;
