/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreateCompanyIndustry } from './userCreateCompanyIndustry';
import type { UserCreateCompanySize } from './userCreateCompanySize';
import type { UserCreateCompanyWebsite } from './userCreateCompanyWebsite';
import type { UserCreateCompanyDescription } from './userCreateCompanyDescription';
import type { UserCreatePrimaryColor } from './userCreatePrimaryColor';
import type { UserCreateSecondaryColor } from './userCreateSecondaryColor';
import type { UserCreateAccentColor } from './userCreateAccentColor';

export interface UserCreate {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  company_name: string;
  company_industry?: UserCreateCompanyIndustry;
  company_size?: UserCreateCompanySize;
  company_website?: UserCreateCompanyWebsite;
  company_description?: UserCreateCompanyDescription;
  primary_color?: UserCreatePrimaryColor;
  secondary_color?: UserCreateSecondaryColor;
  accent_color?: UserCreateAccentColor;
}
