/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { VisualAudioInputResponse } from './visualAudioInputResponse';
import type { VisualAudioInputRecording } from './visualAudioInputRecording';

export interface VisualAudioInput {
  type: 'visual_audio';
  response?: VisualAudioInputResponse;
  recording?: VisualAudioInputRecording;
}
