/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { BodyLoginOauth2ApiAuthLoginOauth2PostGrantType } from './bodyLoginOauth2ApiAuthLoginOauth2PostGrantType';
import type { BodyLoginOauth2ApiAuthLoginOauth2PostClientId } from './bodyLoginOauth2ApiAuthLoginOauth2PostClientId';
import type { BodyLoginOauth2ApiAuthLoginOauth2PostClientSecret } from './bodyLoginOauth2ApiAuthLoginOauth2PostClientSecret';

export interface BodyLoginOauth2ApiAuthLoginOauth2Post {
  grant_type?: BodyLoginOauth2ApiAuthLoginOauth2PostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginOauth2ApiAuthLoginOauth2PostClientId;
  client_secret?: BodyLoginOauth2ApiAuthLoginOauth2PostClientSecret;
}
