/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { CautionConfigDescription } from './cautionConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { CautionConfigDisplay } from './cautionConfigDisplay';
import type { CautionConfigCaution } from './cautionConfigCaution';

export interface CautionConfig {
  label: string;
  description: CautionConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: CautionConfigDisplay;
  caution: CautionConfigCaution;
}
