/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentValidationRequestConfig } from './contentValidationRequestConfig';
import type { ContentValidationRequestContent } from './contentValidationRequestContent';

export interface ContentValidationRequest {
  type: string;
  config: ContentValidationRequestConfig;
  content: ContentValidationRequestContent;
}
