/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentBlockCompletionData } from './contentBlockCompletionData';

export interface ContentBlockCompletion {
  /** Collected data from the content block */
  data: ContentBlockCompletionData;
}
