/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentBlockCreateConfig } from './contentBlockCreateConfig';
import type { ContentBlockCreateContent } from './contentBlockCreateContent';
import type { ContentBlockCreateOrderIndex } from './contentBlockCreateOrderIndex';

export interface ContentBlockCreate {
  /** Content type identifier */
  type: string;
  config: ContentBlockCreateConfig;
  content: ContentBlockCreateContent;
  order_index?: ContentBlockCreateOrderIndex;
}
