/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentBlockProgressConfig } from './contentBlockProgressConfig';
import type { ContentBlockProgressContent } from './contentBlockProgressContent';
import type { ContentBlockProgressData } from './contentBlockProgressData';
import type { ContentBlockProgressStartedAt } from './contentBlockProgressStartedAt';
import type { ContentBlockProgressCompletedAt } from './contentBlockProgressCompletedAt';

export interface ContentBlockProgress {
  id: string;
  type: string;
  config: ContentBlockProgressConfig;
  content: ContentBlockProgressContent;
  order_index: number;
  status: string;
  data?: ContentBlockProgressData;
  started_at?: ContentBlockProgressStartedAt;
  completed_at?: ContentBlockProgressCompletedAt;
}
