/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { SingleChoiceInput } from './singleChoiceInput';
import type { MultipleChoiceInput } from './multipleChoiceInput';
import type { TextInputInput } from './textInputInput';
import type { TextAreaInput } from './textAreaInput';
import type { FileUploadInput } from './fileUploadInput';
import type { ChecklistInput } from './checklistInput';
import type { DateInput } from './dateInput';
import type { TimePickerInput } from './timePickerInput';
import type { RatingScaleInput } from './ratingScaleInput';
import type { VisualAudioInput } from './visualAudioInput';

/**
 * Collected data from the content block
 */
export type ContentBlockCompletionData = SingleChoiceInput | MultipleChoiceInput | TextInputInput | TextAreaInput | FileUploadInput | ChecklistInput | DateInput | TimePickerInput | RatingScaleInput | VisualAudioInput;
