/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentBlockProgressDataAnyOf } from './contentBlockProgressDataAnyOf';

export type ContentBlockProgressData = ContentBlockProgressDataAnyOf | null;
