/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { DateConfigDescription } from './dateConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { DateConfigDisplay } from './dateConfigDisplay';
import type { DateConfigDate } from './dateConfigDate';

export interface DateConfig {
  label: string;
  description: DateConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: DateConfigDisplay;
  date: DateConfigDate;
}
