/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalLinkConfigDescription } from './externalLinkConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { ExternalLinkConfigDisplay } from './externalLinkConfigDisplay';
import type { ExternalLinkConfigLink } from './externalLinkConfigLink';

export interface ExternalLinkConfig {
  label: string;
  description: ExternalLinkConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: ExternalLinkConfigDisplay;
  link: ExternalLinkConfigLink;
}
