/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalLinkBlockUpdateType } from './externalLinkBlockUpdateType';
import type { ExternalLinkBlockUpdateConfig } from './externalLinkBlockUpdateConfig';
import type { ExternalLinkBlockUpdateContent } from './externalLinkBlockUpdateContent';
import type { ExternalLinkBlockUpdateOrderIndex } from './externalLinkBlockUpdateOrderIndex';

export interface ExternalLinkBlockUpdate {
  type?: ExternalLinkBlockUpdateType;
  config?: ExternalLinkBlockUpdateConfig;
  content?: ExternalLinkBlockUpdateContent;
  order_index?: ExternalLinkBlockUpdateOrderIndex;
}
