/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { FileUploadConfigDescription } from './fileUploadConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { FileUploadConfigDisplay } from './fileUploadConfigDisplay';
import type { FileUploadConfigUpload } from './fileUploadConfigUpload';

export interface FileUploadConfig {
  label: string;
  description: FileUploadConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: FileUploadConfigDisplay;
  upload: FileUploadConfigUpload;
}
