/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { HeaderBlockUpdateType } from './headerBlockUpdateType';
import type { HeaderBlockUpdateConfig } from './headerBlockUpdateConfig';
import type { HeaderBlockUpdateContent } from './headerBlockUpdateContent';
import type { HeaderBlockUpdateOrderIndex } from './headerBlockUpdateOrderIndex';

export interface HeaderBlockUpdate {
  type?: HeaderBlockUpdateType;
  config?: HeaderBlockUpdateConfig;
  content?: HeaderBlockUpdateContent;
  order_index?: HeaderBlockUpdateOrderIndex;
}
