/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBlockUpdateType } from './listBlockUpdateType';
import type { ListBlockUpdateConfig } from './listBlockUpdateConfig';
import type { ListBlockUpdateContent } from './listBlockUpdateContent';
import type { ListBlockUpdateOrderIndex } from './listBlockUpdateOrderIndex';

export interface ListBlockUpdate {
  type?: ListBlockUpdateType;
  config?: ListBlockUpdateConfig;
  content?: ListBlockUpdateContent;
  order_index?: ListBlockUpdateOrderIndex;
}
