/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { MultipleChoiceBlockUpdateType } from './multipleChoiceBlockUpdateType';
import type { MultipleChoiceBlockUpdateConfig } from './multipleChoiceBlockUpdateConfig';
import type { MultipleChoiceBlockUpdateContent } from './multipleChoiceBlockUpdateContent';
import type { MultipleChoiceBlockUpdateOrderIndex } from './multipleChoiceBlockUpdateOrderIndex';

export interface MultipleChoiceBlockUpdate {
  type?: MultipleChoiceBlockUpdateType;
  config?: MultipleChoiceBlockUpdateConfig;
  content?: MultipleChoiceBlockUpdateContent;
  order_index?: MultipleChoiceBlockUpdateOrderIndex;
}
