/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { MultipleChoiceConfigDescription } from './multipleChoiceConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { MultipleChoiceConfigDisplay } from './multipleChoiceConfigDisplay';
import type { MultipleChoiceConfigQuestion } from './multipleChoiceConfigQuestion';

export interface MultipleChoiceConfig {
  label: string;
  description: MultipleChoiceConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: MultipleChoiceConfigDisplay;
  question: MultipleChoiceConfigQuestion;
}
