/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { ProgressOverviewCurrentStageId } from './progressOverviewCurrentStageId';
import type { ProgressOverviewCurrentStageName } from './progressOverviewCurrentStageName';
import type { ProgressOverviewStartedAt } from './progressOverviewStartedAt';
import type { ProgressOverviewEstimatedCompletionTime } from './progressOverviewEstimatedCompletionTime';

export interface ProgressOverview {
  session_token: string;
  new_hire_id: string;
  flow_id: string;
  total_stages: number;
  completed_stages: number;
  current_stage_id?: ProgressOverviewCurrentStageId;
  current_stage_name?: ProgressOverviewCurrentStageName;
  overall_progress_percentage: number;
  started_at?: ProgressOverviewStartedAt;
  estimated_completion_time?: ProgressOverviewEstimatedCompletionTime;
}
