/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { RatingScaleBlockUpdateType } from './ratingScaleBlockUpdateType';
import type { RatingScaleBlockUpdateConfig } from './ratingScaleBlockUpdateConfig';
import type { RatingScaleBlockUpdateContent } from './ratingScaleBlockUpdateContent';
import type { RatingScaleBlockUpdateOrderIndex } from './ratingScaleBlockUpdateOrderIndex';

export interface RatingScaleBlockUpdate {
  type?: RatingScaleBlockUpdateType;
  config?: RatingScaleBlockUpdateConfig;
  content?: RatingScaleBlockUpdateContent;
  order_index?: RatingScaleBlockUpdateOrderIndex;
}
