/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { SingleChoiceBlockUpdateType } from './singleChoiceBlockUpdateType';
import type { SingleChoiceBlockUpdateConfig } from './singleChoiceBlockUpdateConfig';
import type { SingleChoiceBlockUpdateContent } from './singleChoiceBlockUpdateContent';
import type { SingleChoiceBlockUpdateOrderIndex } from './singleChoiceBlockUpdateOrderIndex';

export interface SingleChoiceBlockUpdate {
  type?: SingleChoiceBlockUpdateType;
  config?: SingleChoiceBlockUpdateConfig;
  content?: SingleChoiceBlockUpdateContent;
  order_index?: SingleChoiceBlockUpdateOrderIndex;
}
