/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { StageTemplateUpdateName } from './stageTemplateUpdateName';
import type { StageTemplateUpdateDescription } from './stageTemplateUpdateDescription';
import type { StageTemplateUpdateType } from './stageTemplateUpdateType';
import type { StageTemplateUpdateDefaultContent } from './stageTemplateUpdateDefaultContent';
import type { StageTemplateUpdateDefaultConfig } from './stageTemplateUpdateDefaultConfig';
import type { StageTemplateUpdateIsPublic } from './stageTemplateUpdateIsPublic';

export interface StageTemplateUpdate {
  name?: StageTemplateUpdateName;
  description?: StageTemplateUpdateDescription;
  type?: StageTemplateUpdateType;
  default_content?: StageTemplateUpdateDefaultContent;
  default_config?: StageTemplateUpdateDefaultConfig;
  is_public?: StageTemplateUpdateIsPublic;
}
