/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { StageTemplateCreateDescription } from './stageTemplateCreateDescription';
import type { StageTemplateCreateDefaultContentItem } from './stageTemplateCreateDefaultContentItem';
import type { StageTemplateCreateDefaultConfig } from './stageTemplateCreateDefaultConfig';

export interface StageTemplateCreate {
  name: string;
  description?: StageTemplateCreateDescription;
  type: string;
  default_content: StageTemplateCreateDefaultContentItem[];
  default_config: StageTemplateCreateDefaultConfig;
  is_public?: boolean;
}
