/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { StageUpdateName } from './stageUpdateName';
import type { StageUpdateDescription } from './stageUpdateDescription';
import type { StageUpdateType } from './stageUpdateType';
import type { StageUpdateStatus } from './stageUpdateStatus';

export interface StageUpdate {
  name?: StageUpdateName;
  description?: StageUpdateDescription;
  type?: StageUpdateType;
  status?: StageUpdateStatus;
}
