/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TextInputConfigDescription } from './textInputConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { TextInputConfigDisplay } from './textInputConfigDisplay';
import type { TextInputConfigInput } from './textInputConfigInput';

export interface TextInputConfig {
  label: string;
  description: TextInputConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: TextInputConfigDisplay;
  input: TextInputConfigInput;
}
