/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TextAreaBlockUpdateType } from './textAreaBlockUpdateType';
import type { TextAreaBlockUpdateConfig } from './textAreaBlockUpdateConfig';
import type { TextAreaBlockUpdateContent } from './textAreaBlockUpdateContent';
import type { TextAreaBlockUpdateOrderIndex } from './textAreaBlockUpdateOrderIndex';

export interface TextAreaBlockUpdate {
  type?: TextAreaBlockUpdateType;
  config?: TextAreaBlockUpdateConfig;
  content?: TextAreaBlockUpdateContent;
  order_index?: TextAreaBlockUpdateOrderIndex;
}
