/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { TimePickerBlockUpdateType } from './timePickerBlockUpdateType';
import type { TimePickerBlockUpdateConfig } from './timePickerBlockUpdateConfig';
import type { TimePickerBlockUpdateContent } from './timePickerBlockUpdateContent';
import type { TimePickerBlockUpdateOrderIndex } from './timePickerBlockUpdateOrderIndex';

export interface TimePickerBlockUpdate {
  type?: TimePickerBlockUpdateType;
  config?: TimePickerBlockUpdateConfig;
  content?: TimePickerBlockUpdateContent;
  order_index?: TimePickerBlockUpdateOrderIndex;
}
