/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { VisualAudioBlockUpdateType } from './visualAudioBlockUpdateType';
import type { VisualAudioBlockUpdateConfig } from './visualAudioBlockUpdateConfig';
import type { VisualAudioBlockUpdateContent } from './visualAudioBlockUpdateContent';
import type { VisualAudioBlockUpdateOrderIndex } from './visualAudioBlockUpdateOrderIndex';

export interface VisualAudioBlockUpdate {
  type?: VisualAudioBlockUpdateType;
  config?: VisualAudioBlockUpdateConfig;
  content?: VisualAudioBlockUpdateContent;
  order_index?: VisualAudioBlockUpdateOrderIndex;
}
