/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Onboarding-as-a-Service
 * Onboarding-as-a-Service (OaaS) Backend API
 * OpenAPI spec version: 1.0.0
 */
import type { VisualAudioConfigDescription } from './visualAudioConfigDescription';
import type { ValidationConfig } from './validationConfig';
import type { VisualAudioConfigDisplay } from './visualAudioConfigDisplay';
import type { VisualAudioConfigMedia } from './visualAudioConfigMedia';

export interface VisualAudioConfig {
  label: string;
  description: VisualAudioConfigDescription;
  required?: boolean;
  validation: ValidationConfig;
  display: VisualAudioConfigDisplay;
  media: VisualAudioConfigMedia;
}
